config/routes.rb
Rails.application.routes.draw do
root 'users#index'
resources :users, only: [:show] do
  resources :projects
end

get '/', to: 'users#index', as: 'login'
 get '/logout', to: 'sessions#destroy', as: 'logout'
get 'auth/google_oauth2/callback', to: 'sessions#create'
post '/login', to: 'sessions#login'
get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/show', to: 'users#show'
post '/logout', to: 'sessions#destroy'
patch '/users/:user_id/projects', to: 'projects#update'
delete '/logout', to: 'sessions#destroy'
resources :projects
resources :users




end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



end

app/models/location.rb
class Location < ApplicationRecord
  has_many :projects
  has_many :users, through: :projects

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :location

  validates :title, presence: true

  scope :latest, ->(column = :created_at) {order(column => :desc)}

  def user_name
    self.user.name
  end

  def user_name=(name)
    self.user = User.find_or_create_by(name: name)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :locations, through: :projects
  #has_many :photos, :through => :projects
  #has_many :notes, :through => :projects
  has_secure_password :validations => false


  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.first_name = auth.info.first_name
			user.last_name = auth.info.last_name
			user.email = auth.info.email
      user.save!
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  #before_action :authenticate

  #def authenticate
  #  redirect_to :login unless logged_in?
  #end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
      if logged_in?
        @user = current_user
        if @user.nil?
          redirect_to '/'
        else
          @projects = @user.projects
        end
      else
        @projects = Project.all
      end
    end

    def new
      if session[:user_id] && !User.exists?(session[:user_id])
          redirect_to project_path
      else
        @project = Project.new(user_id: session[:user_id])
      end
    end

    def create
       @project = Project.new(project_params)
       if @project.save
         redirect_to @project
       else
         render :new
       end
     end

    def show
      @project = Project.find(params[:id])
      if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      @project = @user.projects.find_by(id: params[:id])
      if @project.nil?
        redirect_to project_path(@user)
      end
    else
    redirect_to '/edit'
    end
  end


 def edit
   if logged_in?
     @user = current_user
     if @user.nil?
       redirect_to '/'
     else
       @project = @user.projects.find_by(params[:id])
       redirect_to edit_project_path if @project.nil?
     end
   else
     @project = Project.find(params[:id])
   end

 end

 def update
    @project = Project.find(params[:id])
    @project.update(project_params)

    if @project.save
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
 end

  private

  def project_params
   params.require(:project).permit(:title, :user_name, :user_id)
 end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :authenticate, only: :create

  def create
  @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    session[:user_id] = @user.id
      redirect_to '/show'
   end

def login
    @user = User.find_by(name: params[:user][:name])
      if @user && @user.authenticate(params[:user][:password])
       session[:user_id] = @user.id
       redirect_to '/show'
     else
       flash[:notice] = "ERROR: Incorrect Name or Password OR Sign Up"
       redirect_to '/'
       end
end


def destroy
  session.delete :user_id
  redirect_to '/'

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def index
  @users = User.all
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)

  if @user.save
    session[:user_id] = @user.id
    redirect_to '/show'
  else
    flash[:notice] = "ERROR: Please Try Again"
    redirect_to '/signup'
  end
end

def show
  @user = current_user
end

def edit
  @user = current_user
end


private

def user_params
  params.require(:user).permit(:name, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
</style>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


  </head>

  <body>
    <div class="w3-top">
      <div class="w3-bar w3-black w3-card">
    <a href="/logout" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right">Log Out</a>
  </div>
</div>
<br>
<br>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<h1>  </h1>
<%= form_for @project do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :designer %>
 <%= f.text_field :user_name || :first_name %>
  <br />

  <%= f.submit %>
<% end %>

<br>
<%= link_to "All Projects", projects_path %>

app/views/projects/edit.html.erb
<h1> Edit Project</h1>
<%= render partial: "form" %>

app/views/projects/index.html.erb
<h1><%= "#{@user.first_name || @user.name}'s Project Page" %></h1>
<ul>
<% @projects.latest.each do |project| %>
  <li><%= link_to project.title, project_path(project) %>
  <%= button_to 'Delete', project_path(project), method: :delete, data: { confirm: "are you sure?"} %></li>
  <br>
<% end %>
</ul>
<br>
<%= link_to "Add New Project", new_project_path(@user) %>

app/views/projects/new.html.erb
<h1> Create a Project </h1>
<%= render partial: "form" %>

app/views/projects/show.html.erb
<h1> Project </h1>
<h3> Title: <%= link_to @project.title, edit_project_path(@project) %></h3>


<%= link_to "All Projects", projects_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <style>
    body {font-family: "Lato", sans-serif}
    .mySlides {display: none}
    </style>


  </head>

  <body>
    <div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a href="https://github.com/Perchitti/rails-project-2" target="_blank" class="w3-bar-item w3-button w3-padding-large w3-hide-small">ProjectBox Github</a>
    <a href="/signup" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right">Sign Up</a>

      </div>
    </div>

<h1> Store your current projects on ProjectBox </h1>


<%= form_for :user, url: '/login' do |f| %>
<%= f.label :name %>
    <%= f.text_field :name, :required => true %>

    <br><br>

    <%= f.label :password %>
    <%= f.password_field :password, :required => true %>

    <br><br>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= f.submit 'Login' %>
<% end %>

<br>

<div class="btn white darken-4 col s10 m4">
     <a href="/auth/google_oauth2" style="text-transform:none">
             <img width="28px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
         Login with Google
     </a>
</div>


</body>
</html>

app/views/users/new.html.erb
<br>
<%= form_for :user, url: '/signup' do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <br>

  <%= f.label :password %>
  <%= f.password_field :password, :required => true %>

  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <%= f.submit "Sign Up" %>

  <% end %>

app/views/users/show.html.erb
<h1><%= "Welcome #{@user.first_name || @user.name}!" %></h1>


<%= link_to "Add New Project", new_project_path(@user) %>
<br>
<br>

<%= link_to "All Projects", projects_path %>